<?php

abstract class Person
{
    /**
     * @var
     */
    protected $firstName;
    protected $lastName;

    /**
     * @param $firstName
     * @param $lastName
     */
    public function __construct($firstName,$lastName)
    {
        $this -> firstName = $firstName;
        $this -> lastName = $lastName;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this -> firstName . ' ' . $this -> lastName;
    }
}

class Employee extends Person
{
    /**
     * @var
     */
    private $salary;
    private $age;

    /**
     * @param $salary
     * @param $age
     * @param $firstName
     * @param $lastName
     */
    public function __construct($salary , $age , $firstName, $lastName)
    {
        parent::__construct($firstName, $lastName);
        $this -> salary = $salary;
        $this -> age = $age;
    }

    /**
     * @return void
     */
    public function getSalary(){}
    public function getAge(){}

    /**
     * @return int|string
     */
    public function __toString()
    {
        return printf("Employee info full name : %s salary %f Age: %d",
        parent::__toString() , $this -> salary , $this -> age); // TODO: Change the autogenerated stub
    }
}

$employee = new Employee(20,25,'Muhammed','Salama');
echo  $employee;

/**
 * Abstraction Properties & Methods
 */
class Student extends Person
{
    /**
     * @var
     */
    private $department;
    private $age;
    private $address;

    /**
     * @param $firstName
     * @param $lastName
     * @param $department
     * @param $age
     * @param $address
     */
    public function __construct($firstName, $lastName,$department,$age,$address)
    {
        parent::__construct($firstName, $lastName);
        $this -> department = $department;
        $this -> age = $age;
        $this -> address = $address;
    }

    /**
     * @return void
     */
    public function getSalary(){}

    /**
     * @return mixed|void
     */
    public function getAge()
    {
        return $this -> age;
    }

    /**
     * @return mixed|void
     */
    public function getDepartment()
    {
        return $this -> department;
    }

    /**
     * @return mixed|void
     */
    public function getAddress()
    {
        return $this -> address;
    }

    /**
     * @return int|string
     */
    public function __toString()
    {
        return printf("Employee Info Full name : %s Department : %s Age : %d address : %s" ,
        Parent::__toString(),$this -> department , $this -> age , $this -> address);
    }
}

echo '<br><br><br>';
$student = new Student('Muhammed','Salama','PHP Developer',25,'Cairo - Egypt');
echo $student;